name: Build and Package

on:
  push:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build extension
        run: npm run build:prod

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: npm run package

      - name: Upload VSIX package
        uses: actions/upload-artifact@v5
        with:
          name: gitstash-vsix
          path: '*.vsix'
